# Generated by Django 6.0.6 on 2026-06-14 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration', models.IntegerField(choices=[(3, '3 mois'), (6, '6 mois'), (12, '12 mois')])),
                ('purpose', models.TextField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='credits/documents/')),
                ('eligibility_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En analyse'), ('APPROUVEE', 'Approuvée'), ('DECAISSEE', 'Décaissée')], default='SOUMISE', max_length=20)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('repayment_start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Microcrédit',
                'verbose_name_plural': 'Microcrédits',
                'ordering': ['-created_at'],
            },
        ),
    ]
