# Generated by Django 6.0.6 on 2026-06-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En analyse'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('DECAISSEE', 'Décaissée')], default='SOUMISE', max_length=20),
        ),
    ]
