# Generated by Django 6.0.6 on 2026-06-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_alter_credit_status'),
        ('remboursements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remboursement',
            name='interest',
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant dû')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('RETARD', 'En retard')], default='EN_ATTENTE', max_length=20)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='credits.credit')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéances',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='remboursement',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='remboursements.repaymentschedule', verbose_name='Échéance concernée'),
        ),
    ]
