# Generated by Django 6.0.6 on 2026-06-16 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='0 = Pas du tout satisfait, 10 = Extrêmement satisfait', verbose_name='Score NPS (0-10)')),
                ('comment', models.TextField(blank=True, help_text='Avez-vous des suggestions ?', verbose_name='Commentaire')),
                ('context_type', models.CharField(choices=[('CREDIT', 'Crédit'), ('ASSURANCE', 'Assurance'), ('CHAT', 'Support client')], max_length=20, verbose_name='Contexte')),
                ('context_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de réponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Réponse NPS',
                'verbose_name_plural': 'Réponses NPS',
                'ordering': ['-created_at'],
            },
        ),
    ]
